exclude:
- .*/fdsfdsfdsfds/fdsfdsfdsfdsfds/fdsfdsfsdfsfds/fdsfdsfdsfdsfdsfaads/fdsafdsafsadfdsafas/fdsafdsafdsafdsaf/fdsafsdafdsa/fdsfdsfsdfsdfsdfds/fdsfsdfsfafdsaf/fdsafsafdsafdsafdsafsda/newrelic[.]js
component_depth: 4
languages: 
- java
